name: explore
on  : [push]
jobs:
  explore:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v1

      - name: "attach git head"
        run: git checkout "${GITHUB_REF#refs/heads/}"

      - name: "exploring..."
        run: |
          echo "    github.action       : ${{github.action}}"

