name: explore
on  : [push]
jobs:
  explore:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v1

      - name: "attach git head"
        run: git checkout "${GITHUB_REF#refs/heads/}"

      - name: "exploring..."
        run: |
          echo "    github                  : ${{github}}"
          echo "    github.action           : ${{github.action}}"
          echo "    github.action_path      : ${{github.action_path}}"
          echo "    github.actor            : ${{github.actor}}"
          echo "    github.base_ref         : ${{github.base_ref}}"
          echo "    github.event            : ${{github.event}}"
          echo "    github.event_name       : ${{github.event_name}}"
          echo "    github.event_path       : ${{github.event_path}}"
          echo "    github.head_ref         : ${{github.head_ref}}"
          echo "    github.job              : ${{github.job}}"
          echo "    github.ref              : ${{github.ref}}"
          echo "    github.repository       : ${{github.repository}}"
          echo "    github.repository_owner : ${{github.repository_owner}}"
          echo "    github.run_id           : ${{github.run_id}}"
          echo "    github.run_number       : ${{github.run_number}}"
          echo "    github.sha              : ${{github.sha}}"
          echo "    github.token            : ${{github.token}}"
          echo "    github.workflow         : ${{github.workflow}}"
          echo "    github.workspace        : ${{github.workspace}}"
          echo "GITHUB_TOKEN=${GITHUB_TOKEN:-alas not set}"
          set | fgrep '${{github.token}}' || echo "no token in env"
          set | fgrep -i github
          
          #find / -type f ! -name \*.jar ! -name \*.zip -exec fgrep '${{github.token}}' {} + 2>/dev/null
          ls -l /*

